
function [freqEndpoints, fit_freq] = getFitFreq()
% spectral partition from Frontiers work
freqEndpoints = [            ...
   0.2           ...
   0.2*sqrt(2.5) ...
   0.5           ...
   0.5*sqrt(2)   ...
   1             ...
   1*sqrt(2)     ...
   2             ...
   2*sqrt(2.5)   ...
   5             ...
   5*sqrt(2)     ...
   10            ...
   10*sqrt(2)    ...
   20            ...
   20*sqrt(2.5)  ...
   50            ...
   50*sqrt(2)    ...
   100           ...
   100*sqrt(2)   ...
   200           ...
%   200*sqrt(2.5) ...
%   500           ...
] ;

fit_freq = [] ;
for i = 1:(length(freqEndpoints) - 1)
   for j = (i + 1):length(freqEndpoints)
      fit_freq = [fit_freq ; freqEndpoints(i) freqEndpoints(j)] ;
   end
end
